- hosts: sandbox 
  gather_facts: False

  tasks:
    - name: Add R 3.5 repos
      apt_repository:
        repo: deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/
      become: yes

    - name: Update and install R
      apt:
        name: "{{ packages }}" 
        update_cache: yes
        allow_unauthenticated: yes
      vars: 
        packages:
          - r-base
          - r-base-dev
          - tmux
          - htop
          - gdebi-core
          - libssl-dev
          - libxml2-dev
          - libcurl4-gnutls-dev
          - texlive
          - texlive-latex-extra
          - texlive-full
      become: yes

    - name: apt-get clean
      apt:
        autoclean: yes
        autoremove: yes
      become: yes

    - name: remove apt lists
      file: 
        path: "{{ dirs }}"
        state: absent
        follow: yes
      become: yes
      vars:
        dirs:
          - /var/lib/apt/lists/* 
          - /tmp/* 
          - /var/tmp/*

    - name: Create Rstudio user/password
      user:
        name: rstudio
        password: $6$eHhqjduJIKoprCNK$8XLBjszNn8Az8uVG9wN70QQUkEvmKGKA74OQxQF6UNcQ85AoyVrgGYz6w0xAW9kJ2cag29UEWCwYfdvYMFyQX1
      become: yes

    - name: Download RStudio
      get_url: 
        url: https://download2.rstudio.org/rstudio-server-1.1.456-amd64.deb
        dest: /home/ubuntu/rstudio-server-1.1.456-amd64.deb

    - name: Install RStudio
      command: gdebi rstudio-server-1.1.456-amd64.deb
      become: yes

    - name: copy ssh key with owner and permissions
      copy:
        src: /Users/bryanyu/.ssh/id_rsa
        dest: /home/rstudio/.ssh/id_rsa
        mode: 0600
        owner: rstudio
        group: rstudio
      become: yes
         
