- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: ybryan
    group_id: sg-6e653e10
    image: ami-759bc50a
    vpc_subnet_id: subnet-924bc6da

  tasks:
    - name: Provision instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: t2.2xlarge
         image: "{{ image }}"
         wait: true
         instance_tags:
           Name: rstudio 
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         volumes:
           - device_name: /dev/sda1 
             volume_type: gp2
             volume_size: 75
             delete_on_termination: true
      register: ec2

    - name: All instance private IP to host group
      add_host: 
        hostname: "{{ item.private_dns_name }}"
        groupname: sandbox
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.private_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"
